---
- name: Ensure phpMyAdmin is installed.
  apt: name=phpmyadmin state=installed
  notify: restart apache

- name: Ensure phpMyAdmin config file is included in Apache config.
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    regexp: "^Include.+phpmyadmin.+$"
    line: "Include /etc/phpmyadmin/apache.conf"
    insertafter: "EOF"
  notify: restart apache

- name: Configure Apache Alias/Security
  template:
    src: "phpmyadmin-confd-{{ ansible_os_family }}.j2"
    dest: /etc/phpmyadmin/apache.conf
  notify: restart apache